language: julia
os:
    - linux
julia:
    - 0.6
    - 0.7
    - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
before_script:
    - julia -e 'if VERSION >= v"0.7-"; using Pkg; Pkg.add("JuMP#master"); else Pkg.add("JuMP"); Pkg.checkout("JuMP"); end'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    # push coverage results to Codecov
    - julia -e 'cd(Pkg.dir("ParameterJuMP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
