language: julia
os:
    - linux
julia:
    - 0.6
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
before_script:
    - julia -e 'Pkg.add("MathOptInterface")'
    - julia -e 'Pkg.add("JuMP")'
    - julia -e 'Pkg.checkout("JuMP")'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    # push coverage results to Codecov
    - julia -e 'cd(Pkg.dir("ParameterJuMP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
